name       : python-distlib
version    : 0.3.6
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/d/distlib/distlib-0.3.6.tar.gz : 14bad2d9b04d3a36127ac97f30b12a19268f211063d8f8ee4f47108896e11b46
homepage   : https://bitbucket.org/pypa/distlib
license    : PSF-2.0
component  : programming.python
summary    : Low-level components of distutils2/packaging
description: |
    Low-level parts of packaging/distutils2 which implement the relevant PEPs and which could be used by third-party packaging tools to achieve interoperability, enhanced with additional features for dependency resolution, package resource management and more.
networking : yes # Check
builddeps  :
    - python-build
    - python-installer
    - python-pytest
    - python-wheel
setup      : |
    rm distlib/*.exe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    export PYTHONHASHSEED=0
    %python3_test pytest3
