name       : python-distlib
version    : 0.3.3
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/d/distlib/distlib-0.3.3.zip : d982d0751ff6eaaab5e2ec8e691d949ee80eddf01a62eaa96ddb11531fe16b05
homepage   : https://bitbucket.org/pypa/distlib
license    : PSF-2.0
component  : programming.python
summary    : Low-level components of distutils2/packaging
description: |
    Low-level parts of packaging/distutils2 which implement the relevant PEPs and which could be used by third-party packaging tools to achieve interoperability, enhanced with additional features for dependency resolution, package resource management and more.
networking : yes # Check
builddeps  :
    - python-pytest
setup      : |
    rm distlib/*.exe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    rm tests/test_shutil.py*
    rm tests/test_sysconfig.py*
    rm -r tests/unittest2
    export PYTHONHASHSEED=0
    %python3_test pytest3
