name       : python-distlib
version    : 0.3.7
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/d/distlib/distlib-0.3.7.tar.gz : 9dafe54b34a028eafd95039d5e5d4851a13734540f1331060d31c9916e7147a8
homepage   : https://bitbucket.org/pypa/distlib
license    : PSF-2.0
component  : programming.python
summary    : Low-level components of distutils2/packaging
description: |
    Low-level parts of packaging/distutils2 which implement the relevant PEPs and which could be used by third-party packaging tools to achieve interoperability, enhanced with additional features for dependency resolution, package resource management and more.
networking : yes # Check
builddeps  :
    - python-build
    - python-installer
    - python-pytest    # check
    - python-wheel
setup      : |
    rm distlib/*.exe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    export PYTHONHASHSEED=0
    %python3_test pytest -v
