name       : python-distlib
version    : 0.3.2
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/d/distlib/distlib-0.3.2.zip : 106fef6dc37dd8c0e2c0a60d3fca3e77460a48907f335fa28420463a6f799736
homepage   : https://bitbucket.org/pypa/distlib
license    : PSF-2.0
component  : programming.python
summary    : Low-level components of distutils2/packaging
description: |
    Low-level parts of packaging/distutils2 which implement the relevant PEPs and which could be used by third-party packaging tools to achieve interoperability, enhanced with additional features for dependency resolution, package resource management and more.
networking : yes # Check
builddeps  :
    - python-pytest
setup      : |
    rm distlib/*.exe
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    rm tests/test_shutil.py*
    rm tests/test_sysconfig.py*
    rm -r tests/unittest2
    export PYTHONHASHSEED=0
    %python3_test pytest3
